loss_fn: !!python/object:torch.nn.modules.loss.BCEWithLogitsLoss
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - - - weight
      - null
    - - pos_weight
      - null
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  reduction: mean
  training: true
lr_scheduler: !!python/object:torch.optim.lr_scheduler.StepLR
  _get_lr_called_within_step: false
  _last_lr:
  - 0.03
  _step_count: 1
  base_lrs:
  - 0.03
  gamma: 0.0001
  last_epoch: 0
  optimizer: &id009 !!python/object:torch.optim.adam.Adam
    defaults:
      amsgrad: false
      betas: &id001 !!python/tuple
      - 0.9
      - 0.999
      eps: 1.0e-08
      lr: 0.03
      weight_decay: 0
    param_groups:
    - amsgrad: false
      betas: *id001
      eps: 1.0e-08
      initial_lr: 0.03
      lr: 0.03
      params:
      - &id003 !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYDwAAADE0MDM4MDEwNjY0NTUzNnECWAMAAABjcHVxA0sITnRxBFEugAJdcQBYDwAAADE0
              MDM4MDEwNjY0NTUzNnEBYS4IAAAAAAAAAL3oGD8LzHw/78umv6nKgD2XHbY85giFPMsIDz9vOG2/
          - 0
          - !!python/tuple
            - 4
            - 2
          - !!python/tuple
            - 2
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - true
        - !!python/object/apply:collections.OrderedDict
          - []
      - &id004 !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYDwAAADE0MDM4MDEwNjUyNTAyNHECWAMAAABjcHVxA0sETnRxBFEugAJdcQBYDwAAADE0
              MDM4MDEwNjUyNTAyNHEBYS4EAAAAAAAAAE0cJb9Yz5e+/a/6P3252L0=
          - 0
          - !!python/tuple
            - 4
          - !!python/tuple
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - true
        - !!python/object/apply:collections.OrderedDict
          - []
      - &id005 !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYDwAAADE0MDM4MDEwMzUwODU0NHECWAMAAABjcHVxA0sgTnRxBFEugAJdcQBYDwAAADE0
              MDM4MDEwMzUwODU0NHEBYS4gAAAAAAAAABmOyb6p4HS+wOydPxykuL6Dm2U/fkdCPxVYUL8W3kc/
              CYV5PTKaFL9rMGi/XoFZvhVsGD2pRaC+2WQov2uW677Yr1g+eNC7PvkAFz1E7jY/VIwrvwZf9z3N
              +IG/FszUPSBm5r1YCfq+3G/1vmIIj762/rw+4RuOPn74i75jdL0+
          - 0
          - !!python/tuple
            - 8
            - 4
          - !!python/tuple
            - 4
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - true
        - !!python/object/apply:collections.OrderedDict
          - []
      - &id006 !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYDwAAADE0MDM4MDEwMzQ5Njg4MHECWAMAAABjcHVxA0sITnRxBFEugAJdcQBYDwAAADE0
              MDM4MDEwMzQ5Njg4MHEBYS4IAAAAAAAAAFzf5z/X2c2/i9MuP0gM971H1iO/vxH6PbYgob5sYWW/
          - 0
          - !!python/tuple
            - 8
          - !!python/tuple
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - true
        - !!python/object/apply:collections.OrderedDict
          - []
      - &id007 !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYDwAAADE0MDM4MDEwMTMxNjM4NHECWAMAAABjcHVxA0sITnRxBFEugAJdcQBYDwAAADE0
              MDM4MDEwMTMxNjM4NHEBYS4IAAAAAAAAAF5M4j9KgNy/HQu5vuqLsT1Md4q+0/3mvhRcvL1IMFe+
          - 0
          - !!python/tuple
            - 1
            - 8
          - !!python/tuple
            - 8
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - true
        - !!python/object/apply:collections.OrderedDict
          - []
      - &id008 !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYDwAAADE0MDM4MDEwNjY1OTM0NHECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYDwAAADE0
              MDM4MDEwNjY1OTM0NHEBYS4BAAAAAAAAAMKemz8=
          - 0
          - !!python/tuple
            - 1
          - !!python/tuple
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - true
        - !!python/object/apply:collections.OrderedDict
          - []
      weight_decay: 0
    state: !!python/object/apply:collections.defaultdict
    - !!python/name:builtins.dict ''
  step_size: 10
  verbose: false
metrics_dict:
  acc: !!python/object:torchkeras.metrics.Accuracy
    _LIGHTNING_GREATER_EQUAL_1_3: true
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - []
    _cache: null
    _computed: null
    _defaults:
      correct: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
          ZQpxAVgPAAAAMTQwMzgwMTAyMDc1MDI0cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgPAAAAMTQw
          MzgwMTAyMDc1MDI0cQFhLgEAAAAAAAAAAAAAAAAAAAA=
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      total: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
          ZQpxAVgPAAAAMTQwMzgwMTAxMjg3Mzc2cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgPAAAAMTQw
          MzgwMTAxMjg3Mzc2cQFhLgEAAAAAAAAAAAAAAAAAAAA=
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    _device: !!python/object/apply:torch.device
    - cpu
    _forward_cache: null
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _is_synced: false
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - []
    _non_persistent_buffers_set: !!set {}
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _persistent:
      correct: false
      total: false
    _reductions:
      correct: &id002 !!python/name:torchmetrics.utilities.data.dim_zero_sum ''
      total: *id002
    _should_unsync: true
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _to_sync: true
    _update_called: false
    compute_on_step: true
    correct: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
        ZQpxAVgPAAAAMTQwMzgwMTA2NDI5OTY4cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgPAAAAMTQw
        MzgwMTA2NDI5OTY4cQFhLgEAAAAAAAAAAAAAAAAAAAA=
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    dist_sync_fn: null
    dist_sync_on_step: false
    process_group: null
    total: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
        ZQpxAVgPAAAAMTQwMzgwMTA0MTg5NzEycQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgPAAAAMTQw
        MzgwMTA0MTg5NzEycQFhLgEAAAAAAAAAAAAAAAAAAAA=
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    training: true
net: !!python/object:__main__.Net
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - - - fc1
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _is_full_backward_hook: null
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - *id003
          - - bias
            - *id004
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 2
        out_features: 4
        training: true
    - - fc2
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _is_full_backward_hook: null
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - *id005
          - - bias
            - *id006
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 4
        out_features: 8
        training: true
    - - fc3
      - !!python/object:torch.nn.modules.linear.Linear
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _is_full_backward_hook: null
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - - - weight
            - *id007
          - - bias
            - *id008
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        in_features: 8
        out_features: 1
        training: true
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  training: true
optimizer: *id009
